name: github action cicd pipeline
on:
    push:
        branches:
        - main
jobs:
    cicdtest:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Build and Push Docker Image
          run: |
            docker build -t myimage .
            echo "${{ secrets.DUCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker tag myimage saur666/myimage
            docker push saur666/myimage

        - name: Connect to EC2
          run: |
            ssh -o "StrictHostKeyChecking=no" -i /tmp/ssh_key  ubuntu@54.255.205.49 "
            kubectl delete deployment my-deployment
            kubectl apply -f /home/ubuntu/my-deployment.yml
            "
